# Generated by Django 5.2.5 on 2025-08-31 07:06

import django.core.validators
import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture for your resume (optional)', null=True, upload_to=resumes.models.resume_profile_pic_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'], message='Only image files (JPEG, PNG, GIF) are allowed.')]),
        ),
    ]
