# Generated by Django 5.2.5 on 2025-09-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='full_name',
        ),
    ]
