# Generated by Django 5.2.5 on 2025-09-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_resume_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='_full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
