# Generated by Django 5.2.5 on 2025-09-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume__full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade_type',
            field=models.CharField(blank=True, choices=[('cgpa', 'CGPA (out of 10)'), ('percentage', 'Percentage (%)'), ('gpa', 'GPA (out of 4)')], help_text='Type of grade (CGPA/Percentage/GPA)', max_length=20, null=True),
        ),
    ]
