# Generated by Django 5.2.5 on 2025-09-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0005_alter_education_grade_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="template",
            field=models.CharField(
                choices=[("modern", "Modern")], default="modern", max_length=20
            ),
        ),
    ]
