# Generated by Django 5.2.4 on 2025-08-11 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_licenseapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='licenseapplication',
            old_name='reviewed_at',
            new_name='processed_at',
        ),
        migrations.RemoveField(
            model_name='licenseapplication',
            name='details',
        ),
        migrations.RemoveField(
            model_name='licenseapplication',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='message',
            field=models.TextField(blank=True, help_text='Additional information from the applicant'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
