# Generated by Django 5.2.4 on 2025-08-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_rename_reviewed_at_licenseapplication_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='message',
            field=models.TextField(blank=True, help_text='Additional information from the applicant (optional)', null=True),
        ),
    ]
