# Generated by Django 5.2.5 on 2025-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
