# Generated by Django 5.2.5 on 2025-09-24 15:14

import uuid
from django.db import migrations, models


def generate_view_tokens(apps, schema_editor):
    """Generate view tokens for existing invoices"""
    Invoice = apps.get_model('invoice_app', 'Invoice')
    for invoice in Invoice.objects.all():
        if not invoice.view_token:
            invoice.view_token = uuid.uuid4()
            invoice.save(update_fields=['view_token'])


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0002_invoice_sent_date"),
    ]

    operations = [
        # Step 1: Add the field as nullable and non-unique first
        migrations.AddField(
            model_name='invoice',
            name='view_token',
            field=models.UUIDField(null=True, blank=True, db_index=True),
        ),
        
        # Step 2: Generate tokens for existing records
        migrations.RunPython(generate_view_tokens, reverse_code=migrations.RunPython.noop),
        
        # Step 3: Alter the field to be non-null and unique
        migrations.AlterField(
            model_name='invoice',
            name='view_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True),
        ),
    ]
