# Generated by Django 5.2.5 on 2025-08-31 07:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture. Will be automatically resized.', null=True, upload_to=accounts.models.user_profile_pic_path, verbose_name='profile picture'),
        ),
    ]
